<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\FormField;

class FormFieldsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $fields = [
            // Required default fields
            [
                'name' => 'school_name',
                'label' => 'School Name',
                'type' => 'text',
                'is_required' => true,
                'is_default' => true,
                'options' => null,
                'validation_rules' => 'required|string|max:255',
                'placeholder' => 'Enter your school name',
                'help_text' => 'Official name of your educational institution',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'email',
                'label' => 'School Email',
                'type' => 'email',
                'is_required' => true,
                'is_default' => true,
                'options' => null,
                'validation_rules' => 'required|email|max:255',
                'placeholder' => 'school@example.com',
                'help_text' => 'Official email address for school communications',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'phone',
                'label' => 'Phone Number',
                'type' => 'phone',
                'is_required' => true,
                'is_default' => true,
                'options' => null,
                'validation_rules' => 'required|string|max:20',
                'placeholder' => '+1 (555) 123-4567',
                'help_text' => 'Primary contact number for the school',
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'domain',
                'label' => 'Domain Name',
                'type' => 'text',
                'is_required' => true,
                'is_default' => true,
                'options' => null,
                'validation_rules' => 'required|string|max:100|unique:schools,domain',
                'placeholder' => 'myschool',
                'help_text' => 'Unique subdomain for your school (e.g., myschool.localhost)',
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'name' => 'address',
                'label' => 'School Address',
                'type' => 'textarea',
                'is_required' => true,
                'is_default' => true,
                'options' => null,
                'validation_rules' => 'required|string|max:500',
                'placeholder' => 'Enter complete school address',
                'help_text' => 'Full postal address of the school',
                'sort_order' => 5,
                'is_active' => true,
            ],
            [
                'name' => 'logo',
                'label' => 'School Logo',
                'type' => 'file',
                'is_required' => false,
                'is_default' => true,
                'options' => null,
                'validation_rules' => 'nullable|image|max:2048',
                'placeholder' => 'Upload school logo',
                'help_text' => 'Upload your school logo (max 2MB, JPG/PNG)',
                'sort_order' => 6,
                'is_active' => true,
            ],
            [
                'name' => 'tagline',
                'label' => 'School Tagline',
                'type' => 'text',
                'is_required' => false,
                'is_default' => true,
                'options' => null,
                'validation_rules' => 'nullable|string|max:255',
                'placeholder' => 'Enter school motto or tagline',
                'help_text' => 'A brief motto or tagline for your school',
                'sort_order' => 7,
                'is_active' => true,
            ],

            // Optional custom fields
            [
                'name' => 'principal_name',
                'label' => 'Principal Name',
                'type' => 'text',
                'is_required' => false,
                'is_default' => false,
                'options' => null,
                'validation_rules' => 'nullable|string|max:255',
                'placeholder' => 'Enter principal\'s full name',
                'help_text' => 'Name of the school principal or head',
                'sort_order' => 8,
                'is_active' => true,
            ],
            [
                'name' => 'establishment_year',
                'label' => 'Establishment Year',
                'type' => 'number',
                'is_required' => false,
                'is_default' => false,
                'options' => null,
                'validation_rules' => 'nullable|integer|min:1800|max:' . date('Y'),
                'placeholder' => 'YYYY',
                'help_text' => 'Year when the school was established',
                'sort_order' => 9,
                'is_active' => true,
            ],
            [
                'name' => 'student_capacity',
                'label' => 'Student Capacity',
                'type' => 'number',
                'is_required' => false,
                'is_default' => false,
                'options' => null,
                'validation_rules' => 'nullable|integer|min:1',
                'placeholder' => 'Enter maximum student capacity',
                'help_text' => 'Maximum number of students the school can accommodate',
                'sort_order' => 10,
                'is_active' => true,
            ],
            [
                'name' => 'school_type',
                'label' => 'School Type',
                'type' => 'select',
                'is_required' => false,
                'is_default' => false,
                'options' => [
                    'primary' => 'Primary School',
                    'secondary' => 'Secondary School',
                    'higher_secondary' => 'Higher Secondary School',
                    'university' => 'University/College'
                ],
                'validation_rules' => 'nullable|string|in:primary,secondary,higher_secondary,university',
                'placeholder' => 'Select school type',
                'help_text' => 'Type of educational institution',
                'sort_order' => 11,
                'is_active' => true,
            ],
            [
                'name' => 'board_affiliation',
                'label' => 'Board Affiliation',
                'type' => 'text',
                'is_required' => false,
                'is_default' => false,
                'options' => null,
                'validation_rules' => 'nullable|string|max:255',
                'placeholder' => 'e.g., CBSE, ICSE, State Board',
                'help_text' => 'Educational board or university affiliation',
                'sort_order' => 12,
                'is_active' => true,
            ],
            [
                'name' => 'license_number',
                'label' => 'License Number',
                'type' => 'text',
                'is_required' => false,
                'is_default' => false,
                'options' => null,
                'validation_rules' => 'nullable|string|max:100',
                'placeholder' => 'Enter government license number',
                'help_text' => 'Government registration or license number',
                'sort_order' => 13,
                'is_active' => true,
            ],
            [
                'name' => 'support_email',
                'label' => 'Support Email',
                'type' => 'email',
                'is_required' => false,
                'is_default' => false,
                'options' => null,
                'validation_rules' => 'nullable|email|max:255',
                'placeholder' => 'support@school.com',
                'help_text' => 'Email address for technical support inquiries',
                'sort_order' => 14,
                'is_active' => true,
            ],
            [
                'name' => 'website',
                'label' => 'School Website',
                'type' => 'url',
                'is_required' => false,
                'is_default' => false,
                'options' => null,
                'validation_rules' => 'nullable|url|max:255',
                'placeholder' => 'https://www.schoolwebsite.com',
                'help_text' => 'Official school website URL',
                'sort_order' => 15,
                'is_active' => true,
            ],
        ];

        foreach ($fields as $field) {
            FormField::create($field);
        }
    }
}
