<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;

class TenantBooksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create();

        $books = [
            [
                'title' => 'Mathematics for Class 10',
                'author' => 'R.D. Sharma',
                'isbn' => '978-81-219-0123-4',
                'publisher' => 'Dhanpat Rai Publications',
                'category' => 'Mathematics',                'subject' => 'Mathematics',
                'total_copies' => 50,
                'available_copies' => 45,
                'price' => 450.00,
                'rack_number' => 'A-01',
                'description' => 'Comprehensive mathematics textbook for class 10 students covering all CBSE curriculum topics.',
            ],
            [
                'title' => 'Physics Fundamentals',
                'author' => 'H.C. Verma',
                'isbn' => '978-81-219-0124-1',
                'publisher' => 'Bharati Bhawan',
                'category' => 'Science',                'subject' => 'Physics',
                'total_copies' => 40,
                'available_copies' => 38,
                'price' => 520.00,
                'rack_number' => 'B-02',
                'description' => 'Essential physics concepts for higher secondary students.',
            ],
            [
                'title' => 'Chemistry Made Easy',
                'author' => 'O.P. Tandon',
                'isbn' => '978-81-219-0125-8',
                'publisher' => 'G.R. Bathla Publications',
                'category' => 'Science',                'subject' => 'Chemistry',
                'total_copies' => 35,
                'available_copies' => 32,
                'price' => 480.00,
                'rack_number' => 'B-03',
                'description' => 'Complete chemistry guide for competitive exams and board preparation.',
            ],
            [
                'title' => 'English Literature Anthology',
                'author' => 'William Shakespeare',
                'isbn' => '978-81-219-0126-5',
                'publisher' => 'Oxford University Press',
                'category' => 'Literature',                'subject' => 'English',
                'total_copies' => 60,
                'available_copies' => 55,
                'price' => 380.00,
                'rack_number' => 'C-01',
                'description' => 'Collection of classic English literature pieces for secondary students.',
            ],
            [
                'title' => 'History of Ancient India',
                'author' => 'R.S. Sharma',
                'isbn' => '978-81-219-0127-2',
                'publisher' => 'Orient BlackSwan',
                'category' => 'History',                'subject' => 'History',
                'total_copies' => 45,
                'available_copies' => 40,
                'price' => 420.00,
                'rack_number' => 'D-01',
                'description' => 'Detailed study of ancient Indian civilization and culture.',
            ],
            [
                'title' => 'Geography Atlas',
                'author' => 'Khullar G.C.',
                'isbn' => '978-81-219-0128-9',
                'publisher' => 'Kalyani Publishers',
                'category' => 'Geography',                'subject' => 'Geography',
                'total_copies' => 30,
                'available_copies' => 28,
                'price' => 350.00,
                'rack_number' => 'D-02',
                'description' => 'Comprehensive atlas with maps and geographical information.',
            ],
            [
                'title' => 'Biology for Beginners',
                'author' => 'Trueman M.',
                'isbn' => '978-81-219-0129-6',
                'publisher' => 'Trueman Book Company',
                'category' => 'Science',                'subject' => 'Biology',
                'total_copies' => 55,
                'available_copies' => 50,
                'price' => 400.00,
                'rack_number' => 'B-04',
                'description' => 'Introduction to biological sciences for young learners.',
            ],
            [
                'title' => 'Computer Science Basics',
                'author' => 'Sumita Arora',
                'isbn' => '978-81-219-0130-2',
                'publisher' => 'Dhanpat Rai & Co.',
                'category' => 'Computer Science',                'subject' => 'Computer Science',
                'total_copies' => 25,
                'available_copies' => 23,
                'price' => 550.00,
                'rack_number' => 'E-01',
                'description' => 'Programming fundamentals and computer applications.',
            ],
            [
                'title' => 'Art and Craft Handbook',
                'author' => 'Meera Sahni',
                'isbn' => '978-81-219-0131-9',
                'publisher' => 'Creative Arts Publication',
                'category' => 'Arts',                'subject' => 'Art',
                'total_copies' => 20,
                'available_copies' => 18,
                'price' => 280.00,
                'rack_number' => 'F-01',
                'description' => 'Creative projects and techniques for art students.',
            ],
            [
                'title' => 'Physical Education Guide',
                'author' => 'Dr. Raj Kumar',
                'isbn' => '978-81-219-0132-6',
                'publisher' => 'Sports Publications',
                'category' => 'Physical Education',                'subject' => 'Physical Education',
                'total_copies' => 15,
                'available_copies' => 15,
                'price' => 320.00,
                'rack_number' => 'G-01',
                'description' => 'Comprehensive guide to physical fitness and sports.',
            ],
            [
                'title' => 'The Great Gatsby',
                'author' => 'F. Scott Fitzgerald',
                'isbn' => '978-0-7432-7356-5',
                'publisher' => 'Scribner',                'category' => 'Fiction',
                'subject' => null,
                'total_copies' => 25,
                'available_copies' => 22,
                'price' => 299.00,
                'rack_number' => 'C-02',
                'description' => 'Classic American novel for general reading.',
            ],
            [
                'title' => 'To Kill a Mockingbird',
                'author' => 'Harper Lee',
                'isbn' => '978-0-06-112008-4',
                'publisher' => 'Harper Perennial',                'category' => 'Fiction',
                'subject' => null,
                'total_copies' => 30,
                'available_copies' => 28,
                'price' => 350.00,
                'rack_number' => 'C-03',
                'description' => 'Pulitzer Prize-winning novel about justice and morality.',
            ],
            [
                'title' => 'The Alchemist',
                'author' => 'Paulo Coelho',
                'isbn' => '978-0-06-231500-7',
                'publisher' => 'HarperOne',                'category' => 'Philosophy',
                'subject' => null,
                'total_copies' => 20,
                'available_copies' => 18,
                'price' => 275.00,
                'rack_number' => 'H-01',
                'description' => 'Inspirational story about following dreams.',
            ],
            [
                'title' => 'Encyclopedia Britannica Vol 1',
                'author' => 'Various Authors',
                'isbn' => '978-1-59339-292-5',
                'publisher' => 'Encyclopedia Britannica',                'category' => 'Reference',
                'subject' => null,
                'total_copies' => 5,
                'available_copies' => 5,
                'price' => 1200.00,
                'rack_number' => 'R-01',
                'description' => 'Comprehensive reference encyclopedia.',
            ],
            [
                'title' => 'Oxford English Dictionary',
                'author' => 'Oxford University Press',
                'isbn' => '978-0-19-861186-8',
                'publisher' => 'Oxford University Press',                'category' => 'Reference',
                'subject' => null,
                'total_copies' => 10,
                'available_copies' => 10,
                'price' => 800.00,
                'rack_number' => 'R-02',
                'description' => 'Authoritative English language dictionary.',
            ]
        ];        foreach ($books as $bookData) {
            DB::table('books')->insert([
                'title' => $bookData['title'],
                'author' => $bookData['author'],
                'isbn' => $bookData['isbn'],
                'publisher' => $bookData['publisher'],
                'category' => $bookData['category'],
                'subject' => $bookData['subject'],
                'total_copies' => $bookData['total_copies'],
                'available_copies' => $bookData['available_copies'],
                'price' => $bookData['price'],
                'location' => $bookData['rack_number'],
                'description' => $bookData['description'],
                'status' => 'active',
                'publication_year' => $faker->numberBetween(2015, 2023),
                'language' => 'English',
                'edition' => $faker->numberBetween(1, 5),
                'pages' => $faker->numberBetween(100, 500),
                'book_code' => 'BK' . str_pad($faker->unique()->numberBetween(1, 9999), 4, '0', STR_PAD_LEFT),
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $this->command->info('✅ Books seeded successfully!');
    }
}
